network: material
# bounds_type: sphere # sphere or aabb

# mesh: undefined
# reg_diffuse_light: true
# reg_diffuse_light_lambda: 0.1
# reg_mat: true

######loss######
# loss: ["nerf_render", "mat_reg", "s3im"]
loss:
  ex: ["nerf_render", "mat_reg"]
# val_metric: ["mat_render"]
# key_metric_name: psnr
####trainier####
# optimizer_type: adam
# lr_type: warm_up_cos
# lr_cfg:
#   end_warm: 1000
#   end_iter: 100000
# total_step: 100000
# val_interval: 5000
# save_interval: 500
# train_log_step: 10
