appearance_embed_dim: 32
background_color: last_sample
base_res: 16
collider_params:
  far_plane: 6.0
  near_plane: 2.0
disable_scene_contraction: false
distortion_loss_mult: 0.002
enable_collider: true
eval_num_rays_per_chunk: 32768
far_plane: 1000.0
features_per_level: 2
get_inner: false
hidden_dim: 64
hidden_dim_color: 64
hidden_dim_transient: 64
implementation: tcnn
interlevel_loss_mult: 1.0
log2_hashmap_size: 19
loss_coefficients:
  rgb_loss_coarse: 1.0
  rgb_loss_fine: 1.0
max_res: 2048
near_plane: 0.05
num_levels: 16
num_nerf_samples_per_ray: 48
num_proposal_iterations: 2
num_proposal_samples_per_ray:
  - 256
  - 96
orientation_loss_mult: 0.0001
pred_normal_loss_mult: 0.001
predict_normals: false
prompt: null
proposal_initial_sampler: piecewise
proposal_net_args_list:
  - hidden_dim: 16
    log2_hashmap_size: 17
    max_res: 128
    num_levels: 5
    use_linear: false
  - hidden_dim: 16
    log2_hashmap_size: 17
    max_res: 256
    num_levels: 5
    use_linear: false
proposal_update_every: 5
proposal_warmup: 5000
proposal_weights_anneal_max_num_iters: 1000
proposal_weights_anneal_slope: 10.0
use_average_appearance_embedding: true
use_gradient_scaling: false
use_proposal_weight_anneal: true
use_same_proposal_network: false
use_single_jitter: true
